[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.x"
  NPM_VERSION = "10.x"

[dev]
  command = "npm run dev"
  port = 5000
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle 404s properly for Next.js
[[redirects]]
  from = "/*"
  to = "/_next/static/chunks/pages/404.js"
  status = 404

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true